<?php
declare(strict_types=1);

return [
    'start' => [
        'title' => 'Start',
        'description' => 'Seepferdchen‑Garde Schwimmschule in Herzogenrath Region Aachen: Kurse für Kinder ab 5 Jahren – 10× 45 Minuten, individuelle Förderung, Sicherheit und Spaß. Offizielle Seepferdchen‑Prüfung.',
        'cms' => false,
        'nav' => false,
        'nav_label' => 'Start',
        'nav_order' => 10,
        'canonical' => '/',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/start.jpg',
    ],
    'schwimmkurse' => [
        'title' => 'Schwimmkurse',
        'description' => 'Schwimmkurse in kleinen Gruppen: Wassergewöhnung, Grundtechniken und Sicherheit. Vorbereitung auf das Seepferdchen‑Abzeichen.',
        'cms' => true,
        'nav' => true,
        'nav_label' => 'Schwimmkurse',
        'nav_order' => 20,
        'canonical' => '/schwimmkurse',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/schwimmkurse.jpg',
    ],
    'ueber-mich' => [
        'title' => 'Über mich',
        'description' => 'Über mich: Riccardo Nappa, Fachangestellter für Bäderbetriebe – Erfahrung, Sicherheit und Freude am Schwimmenlernen.',
        'cms' => true,
        'nav' => true,
        'nav_label' => 'Über mich',
        'nav_order' => 30,
        'canonical' => '/ueber-mich',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/ueber-mich.jpg',
    ],
    'anmeldung' => [
        'title' => 'Anmeldung',
        'description' => 'Anmeldung und Voranmeldung für Schwimmkurse: teilen Sie mir Kurswunsch, Zeiten und Schwimmniveau mit. Ich melde mich zeitnah.',
        'cms' => false,
        'nav' => true,
        'nav_label' => 'Anmeldung',
        'nav_order' => 40,
        'canonical' => '/anmeldung',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/anmeldung.jpg',
    ],
    'kontakt' => [
        'title' => 'Kontakt',
        'description' => 'Kontakt zur Schwimmschule Seepferdchen‑Garde: Telefon, WhatsApp, E‑Mail oder Kontaktformular. Ich melde mich zeitnah bei Ihnen.',
        'cms' => false,
        'nav' => true,
        'nav_label' => 'Kontakt',
        'nav_order' => 50,
        'canonical' => '/kontakt',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/kontakt.jpg',
    ],
    'impressum' => [
        'title' => 'Impressum',
        'description' => 'Impressum der Schwimmschule Seepferdchen‑Garde – gesetzliche Anbieterkennzeichnung und Kontakt.',
        'cms' => true,
        'nav' => true,
        'nav_label' => 'Impressum',
        'nav_order' => 90,
        'canonical' => '/impressum',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/impressum.jpg',
    ],
    'datenschutz' => [
        'title' => 'Datenschutzerklärung',
        'description' => 'Datenschutzerklärung: Informationen zur Verarbeitung personenbezogener Daten, Kontakt und Rechte.',
        'cms' => true,
        'nav' => true,
        'nav_label' => 'Datenschutz',
        'nav_order' => 100,
        'canonical' => '/datenschutz',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/datenschutz.jpg',
    ],
];
