<?php
declare(strict_types=1);

return [
    'start' => [
        'title' => 'Start',
        'description' => 'Schwimmschule in Herzogenrath (Region Aachen): Kinderschwimmen, Seepferdchen‑Vorbereitung und private Schwimmstunden – sicher, spielerisch, individuell.',
        'keywords' => 'Schwimmschule Herzogenrath, Schwimmkurs Aachen, Kinderschwimmen, Seepferdchen, private Schwimmstunden, Schwimmunterricht, Riccardo Nappa',
        'cms' => false,
        'nav' => false,
        'nav_label' => 'Start',
        'nav_order' => 10,
        'canonical' => '/',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/start.jpg',
    ],
    'schwimmkurse' => [
        'title' => 'Schwimmkurse',
        'description' => 'Individuelle Schwimmkurse auf Anfrage: Kinderschwimmen, Seepferdchen‑Vorbereitung und private Schwimmstunden in Herzogenrath/Aachen. Jetzt Kontakt aufnehmen.',
        'keywords' => 'Schwimmkurse Herzogenrath, Schwimmkurs Aachen, Seepferdchen Kurs, Kinderschwimmen, individueller Schwimmunterricht, private Schwimmstunden',
        'cms' => true,
        'nav' => true,
        'nav_label' => 'Schwimmkurse',
        'nav_order' => 20,
        'canonical' => '/schwimmkurse',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/schwimmkurse.jpg',
    ],
    'ueber-mich' => [
        'title' => 'Über mich',
        'description' => 'Riccardo Nappa – Fachangestellter für Bäderbetriebe. Erfahrung im Kinderschwimmen, sichere Lernumgebung und individuelle Förderung in Herzogenrath/Aachen.',
        'keywords' => 'Riccardo Nappa, Schwimmtrainer Herzogenrath, Fachangestellter für Bäderbetriebe, Kinderschwimmen Aachen, Seepferdchen‑Garde',
        'cms' => true,
        'nav' => true,
        'nav_label' => 'Über mich',
        'nav_order' => 30,
        'canonical' => '/ueber-mich',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/ueber-mich.jpg',
    ],
    'anmeldung' => [
        'title' => 'Anmeldung',
        'description' => 'Anmeldung für individuelle Schwimmkurse und private Schwimmstunden auf Anfrage. Schreiben Sie mir – ich melde mich mit passenden Terminen in Herzogenrath/Aachen.',
        'keywords' => 'Anmeldung Schwimmkurs, Schwimmkurs Anfrage, private Schwimmstunden, individueller Schwimmunterricht, Herzogenrath, Aachen',
        'cms' => false,
        'nav' => true,
        'nav_label' => 'Anmeldung',
        'nav_order' => 40,
        'canonical' => '/anmeldung',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/anmeldung.jpg',
    ],
    'kontakt' => [
        'title' => 'Kontakt',
        'description' => 'Kontakt zur Seepferdchen‑Garde Schwimmschule in Herzogenrath (Aachen): Telefon, WhatsApp, E‑Mail und Kontaktformular. Ich melde mich zeitnah zurück.',
        'keywords' => 'Kontakt Schwimmschule, Schwimmkurs Kontakt, Schwimmschule Herzogenrath, Schwimmkurs Aachen, WhatsApp, E‑Mail',
        'cms' => false,
        'nav' => true,
        'nav_label' => 'Kontakt',
        'nav_order' => 50,
        'canonical' => '/kontakt',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/kontakt.jpg',
    ],
    'impressum' => [
        'title' => 'Impressum',
        'description' => 'Impressum der Seepferdchen‑Garde Schwimmschule: Anbieterkennzeichnung, Kontakt und rechtliche Informationen.',
        'keywords' => 'Impressum Schwimmschule, Seepferdchen‑Garde, Anbieterkennzeichnung, Rechtliche Angaben',
        'cms' => true,
        'nav' => false,
        'nav_label' => 'Impressum',
        'nav_order' => 90,
        'canonical' => '/impressum',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/impressum.jpg',
    ],
    'haftungsausschluss' => [
        'title' => 'Haftungsausschluss',
        'description' => 'Haftungsausschluss der Seepferdchen‑Garde Schwimmschule: Hinweise zur Teilnahme am Schwimmunterricht und zur Haftung.',
        'keywords' => 'Haftungsausschluss Schwimmschule, Teilnahmebedingungen, Haftung, Schwimmunterricht',
        'cms' => true,
        'nav' => false,
        'nav_label' => 'Haftungsausschluss',
        'nav_order' => 95,
        'canonical' => '/haftungsausschluss',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/haftungsausschluss.jpg',
    ],
    'datenschutz' => [
        'title' => 'Datenschutzerklärung',
        'description' => 'Datenschutzerklärung der Seepferdchen‑Garde: Informationen zur Verarbeitung personenbezogener Daten, Kontakt und Rechte (DSGVO).',
        'keywords' => 'Datenschutzerklärung Schwimmschule, DSGVO, Datenschutz, personenbezogene Daten',
        'cms' => true,
        'nav' => false,
        'nav_label' => 'Datenschutz',
        'nav_order' => 100,
        'canonical' => '/datenschutz',
        'robots' => 'index,follow',
        'og_image' => '/assets/og/datenschutz.jpg',
    ],
];
